# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReCasos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oac.Casos')),
            ],
        ),
    ]
