# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oac', '0002_recasos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Casos',
            new_name='Caso',
        ),
        migrations.RenameModel(
            old_name='ReCasos',
            new_name='ReCaso',
        ),
    ]
