# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oac', '0003_auto_20161228_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caso',
            old_name='caso',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='caso',
            name='creado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recaso',
            name='caso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oac.Caso'),
        ),
    ]
