# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oac', '0005_auto_20170122_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='departamento',
            field=models.CharField(choices=[('Despacho', 'Despacho'), ('Personal', 'Personal'), ('Juridica', 'Juridica'), ('Inicial', 'Inicial'), ('Especial', 'Especial'), ('Primaria', 'Primaria'), ('Media General', 'Media General'), ('Educ. para Adultos', 'Educ. para Adultos'), ('H.C.M', 'H.C.M')], max_length=100),
        ),
    ]
