# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oac', '0006_auto_20170122_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='estado',
            field=models.CharField(choices=[('Por atender', 'Por atender'), ('Atendido', 'Atendido'), ('Respondiendo', 'Respondiendo')], default='Por atender', max_length=50, null=True),
        ),
    ]
