# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oac', '0008_auto_20170201_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso',
            name='activo',
        ),
    ]
