# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oac', '0013_datosusuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatosUsuario',
            new_name='PerfilUsuario',
        ),
    ]
