# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oac', '0015_perfilusuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposCasos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(blank=True, choices=[('Despacho', 'Despacho'), ('Personal', 'Personal'), ('Juridica', 'Juridica'), ('Inicial', 'Inicial'), ('Especial', 'Especial'), ('Primaria', 'Primaria'), ('Media General', 'Media General'), ('Educ. para Adultos', 'Educ. para Adultos'), ('H.C.M', 'H.C.M')], max_length=140, null=True)),
                ('caso', models.CharField(max_length=140)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
