# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oac', '0019_caso_nrocaso'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocaso',
            name='preguntasf',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='departamento',
            field=models.CharField(blank=True, choices=[('Despacho', 'Despacho'), ('Personal', 'Personal'), ('Juridica', 'Juridica'), ('Eponimo', 'Eponimo'), ('Pago Directo', 'Pago Directo'), ('Jubilacion', 'Jubilacion'), ('Comunidades Educativas', 'Comunidades Educativas'), ('Notas', 'Notas'), ('Inicial', 'Inicial'), ('Especial', 'Especial'), ('Primaria', 'Primaria'), ('Media General', 'Media General'), ('Educ. para Adultos', 'Educ. para Adultos'), ('H.C.M', 'H.C.M'), ('Atencion OAC', 'Atencion OAC')], max_length=140, null=True),
        ),
    ]
