# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oac', '0004_auto_20161229_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='estado',
            field=models.CharField(choices=[('Por atender', 'Por atender'), ('Atendido', 'Atendido'), ('Respondiendo', 'Respondiendo')], default='Por atender', max_length=50),
        ),
        migrations.AlterField(
            model_name='caso',
            name='departamento',
            field=models.IntegerField(choices=[('Despacho', 'Despacho'), ('Personal', 'Personal'), ('Juridica', 'Juridica'), ('Inicial', 'Inicial'), ('Especial', 'Especial'), ('Primaria', 'Primaria'), ('Media General', 'Media General'), ('Educ. para Adultos', 'Educ. para Adultos'), ('H.C.M', 'H.C.M')]),
        ),
    ]
