# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oac', '0009_remove_caso_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
