# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oac', '0014_auto_20170205_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
