# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oac', '0016_tiposcasos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TiposCasos',
            new_name='TipoCaso',
        ),
    ]
