# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oac', '0017_auto_20170218_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='casotipo',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='caso',
            name='departamento',
            field=models.CharField(choices=[('Despacho', 'Despacho'), ('Personal', 'Personal'), ('Juridica', 'Juridica'), ('Eponimo', 'Eponimo'), ('Pago Directo', 'Pago Directo'), ('Jubilacion', 'Jubilacion'), ('Comunidades Educativas', 'Comunidades Educativas'), ('Notas', 'Notas'), ('Inicial', 'Inicial'), ('Especial', 'Especial'), ('Primaria', 'Primaria'), ('Media General', 'Media General'), ('Educ. para Adultos', 'Educ. para Adultos'), ('H.C.M', 'H.C.M')], max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='departamento',
            field=models.CharField(blank=True, choices=[('Despacho', 'Despacho'), ('Personal', 'Personal'), ('Juridica', 'Juridica'), ('Eponimo', 'Eponimo'), ('Pago Directo', 'Pago Directo'), ('Jubilacion', 'Jubilacion'), ('Comunidades Educativas', 'Comunidades Educativas'), ('Notas', 'Notas'), ('Inicial', 'Inicial'), ('Especial', 'Especial'), ('Primaria', 'Primaria'), ('Media General', 'Media General'), ('Educ. para Adultos', 'Educ. para Adultos'), ('H.C.M', 'H.C.M')], max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='tipocaso',
            name='departamento',
            field=models.CharField(blank=True, choices=[('Despacho', 'Despacho'), ('Personal', 'Personal'), ('Juridica', 'Juridica'), ('Eponimo', 'Eponimo'), ('Pago Directo', 'Pago Directo'), ('Jubilacion', 'Jubilacion'), ('Comunidades Educativas', 'Comunidades Educativas'), ('Notas', 'Notas'), ('Inicial', 'Inicial'), ('Especial', 'Especial'), ('Primaria', 'Primaria'), ('Media General', 'Media General'), ('Educ. para Adultos', 'Educ. para Adultos'), ('H.C.M', 'H.C.M')], max_length=140, null=True),
        ),
    ]
