# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oac', '0018_auto_20170219_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='nrocaso',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
